### PR TITLE
compatible with 7.0 and 7.1

### PR DESCRIPTION
**Pull request by sandeepsingh510**

### CODE REVIEW

**Comment by avstudnitz** [comment]
You could have removed support for PHP 5.5 as well, as no Magento 2 version supports that.

**Comment by peterjaap** [comment]
And add support for PHP 7.2 since a lot of merchants will upgrade to PHP 7.2 when 2.3 hits (because they need to upgrade from 7.0 anwyay so they'll probably skip 7.1).

**Comment by avstudnitz** [comment]
I agree, if someone could test it on PHP 7.2, it would be very helpful to declare compatibility to it.

**Comment by sandeepsingh510** [comment]
Yes  I also agree with you. Magento 2.3 will work with 7.2

**Pull request merged**
